-- =========================================================
-- Lio Pricing — Module Library (team-shared custom modules)
-- =========================================================
-- Run this once in your Supabase SQL editor to enable the
-- Admin Mode "Module Library" feature. After this, everyone
-- with the password can add/edit/delete custom modules and
-- they appear in every team-member's Quote Workspace.
-- ---------------------------------------------------------

create table if not exists public.custom_modules (
  id          bigint generated by default as identity primary key,
  module_key  text  not null unique,        -- e.g. 'cnb_bot' (lowercase, kebab/underscore)
  name        text  not null,
  description text,
  icon        text,                          -- single emoji
  category    text  default 'Custom',        -- buildCalc category bucket
  unit        text,                          -- e.g. 'Negotiations'
  color       text  default 'slate',
  tiers       jsonb not null default '[]',   -- [{ vol, price, eur?, gbp? }, …]
  created_by  text,                          -- Lio sales contact key
  created_at  timestamptz default now(),
  updated_at  timestamptz default now()
);

-- Open RLS for the anon role (this app uses the anon key only — same trust
-- model as the existing `quotes` table; the password gate is the access
-- control). If you want stricter isolation later, swap to a service role.
alter table public.custom_modules enable row level security;

-- Explicit table privileges — REQUIRED for new Supabase projects after
-- May 30, 2026 and enforced on existing projects after Oct 30, 2026.
-- Without these, PostgREST returns 401/403 even when RLS policies allow access.
grant select, insert, update, delete on public.custom_modules to anon, authenticated;
grant usage, select on sequence public.custom_modules_id_seq to anon, authenticated;

drop policy if exists "Anyone can read custom_modules" on public.custom_modules;
create policy "Anyone can read custom_modules"
  on public.custom_modules for select
  using (true);

drop policy if exists "Anyone can insert custom_modules" on public.custom_modules;
create policy "Anyone can insert custom_modules"
  on public.custom_modules for insert
  with check (true);

drop policy if exists "Anyone can update custom_modules" on public.custom_modules;
create policy "Anyone can update custom_modules"
  on public.custom_modules for update
  using (true) with check (true);

drop policy if exists "Anyone can delete custom_modules" on public.custom_modules;
create policy "Anyone can delete custom_modules"
  on public.custom_modules for delete
  using (true);

-- Optional helper trigger: keep updated_at fresh on edit
create or replace function public.touch_updated_at() returns trigger as $$
begin new.updated_at = now(); return new; end;
$$ language plpgsql;

drop trigger if exists trg_custom_modules_touch on public.custom_modules;
create trigger trg_custom_modules_touch
  before update on public.custom_modules
  for each row execute function public.touch_updated_at();
